const SITE={calendly:'https://calendly.com/brainforceai/30min',email:'isaac@thepenscribe.com',phone:'832-449-8631',phoneHref:'+18324498631',linkedin:'https://www.linkedin.com/in/isaac-adetoyese',companyLinkedIn:'https://www.linkedin.com/company/109564075/',upwork:'https://www.upwork.com/freelancers/~018a7b32ee0a61e4d0'};

function shell(){
 const isHome=document.body.classList.contains('template-home');
 const nav=`<nav class="site-nav" id="main-nav"><div class="container nav-wrap"><a class="brand" href="/index.html"><img class="brand-logo logo-day" src="/assets/images/penscribe-logo-day.png" alt="The Penscribe logo"><img class="brand-logo logo-night" src="/assets/images/penscribe-logo-night.png" alt="" aria-hidden="true"><span>THE PENSCRIBE<small>GOVERNMENT CONTRACTS</small></span></a><div class="nav-links" id="nav-links"><a href="/index.html">Home</a><a href="/about.html">About</a><a href="/services.html">Services</a><a href="/contracts.html">Results</a><a href="/insights.html">Insights</a><a href="/contact.html">Contact</a><button class="btn btn-dark" data-book>Book a strategy call ↗</button></div><div class="nav-actions"><button class="theme-toggle" type="button" aria-label="Switch to night mode"><svg class="icon-sun" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg><svg class="icon-moon" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg></button><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="nav-links">${isHome?'Menu':'☰'}</button></div></div></nav>`;
 const footer=`<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="/"><img class="brand-logo logo-night" src="/assets/images/penscribe-logo-night.png" alt="The Penscribe logo"><span>THE PENSCRIBE<small>GOVERNMENT CONTRACTS</small></span></a><p class="muted">Win-ready strategy and proposal development for serious government contractors.</p></div><div><h4>Explore</h4><a href="/index.html">Home</a><a href="/about.html">About Isaac</a><a href="/services.html">Services</a><a href="/contracts.html">Client results</a><a href="/insights.html">Insights</a></div><div><h4>Expertise</h4><a href="/services/proposal-preparation.html">Proposal writing</a><a href="/services/rfp-analysis.html">RFP analysis</a><a href="/services/sam-gov-registration.html">SAM.gov</a><a href="/services/sba-certifications.html">SBA certifications</a></div><div><h4>Connect</h4><a href="mailto:${SITE.email}">${SITE.email}</a><a href="tel:${SITE.phoneHref}">${SITE.phone}</a><a href="${SITE.linkedin}" target="_blank" rel="me noopener">LinkedIn ↗</a><a href="${SITE.companyLinkedIn}" target="_blank" rel="noopener">Company page ↗</a><a href="${SITE.upwork}" target="_blank" rel="me noopener">Upwork ↗</a><a href="/contact.html">Start a conversation</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} The Penscribe Agency. All rights reserved.</span><span>Federal • State • Local</span></div></div></footer>`;
 document.body.insertAdjacentHTML('afterbegin',nav);
 document.body.insertAdjacentHTML('beforeend',footer+`<div class="chat"><div class="chat-panel"><div class="chat-head"><strong>Talk to The Penscribe</strong><div style="font-size:13px;color:#b8c4bd">Typically replies within one hour.</div></div><div class="chat-body"><div>How would you like to connect?</div><a href="${SITE.calendly}" target="_blank" rel="noopener">↗ Book a 30-minute call</a><a href="mailto:${SITE.email}">✉ Email Isaac</a><a href="${SITE.linkedin}" target="_blank" rel="noopener">↗ Message on LinkedIn</a><a href="/contact.html">→ Send a project brief</a></div></div><button class="chat-button" aria-label="Open live chat">✦</button></div><div class="modal" id="booking-modal"><div class="modal-card"><button class="modal-close" aria-label="Close">×</button><div class="eyebrow">Strategy call</div><h2 style="font-size:42px;margin:15px 0">Let's assess your next opportunity.</h2><p class="lead" style="font-size:17px">Share a few details. We will respond with next steps within one hour.</p><form class="form js-contact" data-source="booking"><div class="form-grid"><div class="field"><label>Name</label><input name="name" required autocomplete="name"></div><div class="field"><label>Business email</label><input name="email" required type="email" autocomplete="email"></div><div class="field full"><label>What do you need help with?</label><textarea name="message" rows="4" required></textarea></div><input class="hp" name="website" tabindex="-1" autocomplete="off"><div class="field full"><button class="btn btn-dark" type="submit">Request my consultation →</button><div class="form-status" role="status"></div></div></div></form></div></div><div class="cookie"><strong>Your privacy matters.</strong><div>We use privacy-friendly analytics to improve this site.</div><button class="btn btn-primary">Got it</button></div><div class="cursor-orbit" aria-hidden="true"><span></span></div>`);
}

function init(){
 shell();
 const nav=document.querySelector('.site-nav'),toggle=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');
 addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>8),{passive:true});
 const setMenu=open=>{links.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);toggle.setAttribute('aria-expanded',open);toggle.textContent=document.body.classList.contains('template-home')?(open?'Close':'Menu'):(open?'×':'☰')};toggle.onclick=()=>setMenu(!links.classList.contains('open'));links.addEventListener('click',e=>{if(e.target.closest('a,button'))setMenu(false)});document.addEventListener('click',e=>{if(links.classList.contains('open')&&!e.target.closest('.nav-links,.menu-toggle'))setMenu(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&links.classList.contains('open')){setMenu(false);toggle.focus()}});
 const themeBtn=document.querySelector('.theme-toggle'),applyTheme=t=>{document.documentElement.dataset.theme=t;themeBtn.setAttribute('aria-label',t==='dark'?'Switch to day mode':'Switch to night mode');const m=document.querySelector('meta[name=theme-color]');if(m)m.content=t==='dark'?'#0A0D18':'#FAFAF7'};applyTheme(document.documentElement.dataset.theme==='dark'?'dark':'light');themeBtn.onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';applyTheme(t);try{localStorage.setItem('ps-theme',t)}catch(e){}};matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',e=>{let saved=null;try{saved=localStorage.getItem('ps-theme')}catch(_){}if(!saved)applyTheme(e.matches?'dark':'light')});
 const modal=document.querySelector('.modal');document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{if(SITE.calendly)window.open(SITE.calendly,'_blank','noopener');else modal.classList.add('open')});document.querySelector('.modal-close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
 const chat=document.querySelector('.chat');document.querySelector('.chat-button').onclick=()=>chat.classList.toggle('open');document.querySelectorAll('.js-contact').forEach(form=>form.addEventListener('submit',submitForm));
 if(!localStorage.getItem('ps-cookie'))setTimeout(()=>document.querySelector('.cookie').classList.add('show'),1200);document.querySelector('.cookie button').onclick=()=>{localStorage.setItem('ps-cookie','1');document.querySelector('.cookie').classList.remove('show')};
 const motionItems=[...document.querySelectorAll('[data-scroll-x]')];
 if(motionItems.length&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let motionFrame=0;const updateMotion=()=>{motionFrame=0;motionItems.forEach(el=>{const speed=Number(el.dataset.scrollX)||0,rect=el.getBoundingClientRect(),distance=innerHeight*.5-rect.top;const shift=Math.max(-85,Math.min(85,distance*speed));el.style.translate=`${shift}px 0`})};const queueMotion=()=>{if(!motionFrame)motionFrame=requestAnimationFrame(updateMotion)};addEventListener('scroll',queueMotion,{passive:true});addEventListener('resize',queueMotion);updateMotion()}
 const heroItems=[...document.querySelectorAll('[data-hero-speed]')],words=document.querySelector('.words-section');
 if((heroItems.length||words)&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let scrollFrame=0;const updateScrollScenes=()=>{scrollFrame=0;const y=Math.min(scrollY,innerHeight*1.25);heroItems.forEach(el=>{const speed=Number(el.dataset.heroSpeed)||1;el.style.translate=`0 ${-y*speed*.34}px`});if(words){const r=words.getBoundingClientRect(),progress=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight*.72)));words.style.setProperty('--words-fade',String(1-progress))}};const queueScenes=()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateScrollScenes)};addEventListener('scroll',queueScenes,{passive:true});addEventListener('resize',queueScenes);updateScrollScenes()}
 const programs=[...document.querySelectorAll('.process-program')];if(programs.length){const programObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('active');programObserver.unobserve(entry.target)}}),{threshold:.22,rootMargin:'0px 0px -12%'});programs.forEach(card=>programObserver.observe(card))}
 const cursor=document.querySelector('.cursor-orbit');if(cursor&&matchMedia('(pointer:fine)').matches){let mouseX=-100,mouseY=-100,cursorX=-100,cursorY=-100;const follow=()=>{cursorX+=(mouseX-cursorX)*.2;cursorY+=(mouseY-cursorY)*.2;cursor.style.transform=`translate3d(${cursorX}px,${cursorY}px,0) translate(-50%,-50%)`;requestAnimationFrame(follow)};addEventListener('mousemove',e=>{mouseX=e.clientX;mouseY=e.clientY},{passive:true});addEventListener('mouseover',e=>cursor.classList.toggle('is-link',Boolean(e.target.closest('a,button,.process-program,.process-image-card'))));follow()}
 const liveHero=document.querySelector('.reference-hero');if(liveHero&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const moveHero=e=>{const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;liveHero.style.setProperty('--hero-copy-x',`${x*14}px`);liveHero.style.setProperty('--hero-copy-y',`${y*8}px`);liveHero.style.setProperty('--hero-last-x',`${x*-9}px`);liveHero.style.setProperty('--hero-last-y',`${y*-5}px`);liveHero.style.setProperty('--hero-image-x',`${x*-10}px`);liveHero.style.setProperty('--hero-image-y',`${y*-6}px`);liveHero.style.setProperty('--hero-orbit-x',`${x*32}px`);liveHero.style.setProperty('--hero-orbit-y',`${y*24}px`);liveHero.style.setProperty('--hero-cross-x',`${x*-24}px`);liveHero.style.setProperty('--hero-cross-y',`${y*-18}px`);liveHero.style.setProperty('--hero-dots-x',`${x*42}px`);liveHero.style.setProperty('--hero-dots-y',`${y*-30}px`)};liveHero.addEventListener('pointermove',moveHero,{passive:true});liveHero.addEventListener('pointerleave',()=>['--hero-copy-x','--hero-copy-y','--hero-last-x','--hero-last-y','--hero-image-x','--hero-image-y','--hero-orbit-x','--hero-orbit-y','--hero-cross-x','--hero-cross-y','--hero-dots-x','--hero-dots-y'].forEach(name=>liveHero.style.setProperty(name,'0px')))}
 const counters=[...document.querySelectorAll('.count-up')];if(counters.length){const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||entry.target.dataset.counted)return;entry.target.dataset.counted='1';const el=entry.target,target=Number(el.dataset.count),decimals=Number(el.dataset.decimals||0),prefix=el.dataset.prefix||'',suffix=el.dataset.suffix||'',started=performance.now(),duration=1700;const tick=now=>{const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,3),value=target*eased;el.textContent=prefix+value.toLocaleString('en-US',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})+suffix;if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterObserver.unobserve(el)}),{threshold:.45});counters.forEach(el=>counterObserver.observe(el))}
 const rvSlider=document.querySelector('.review-slider');
 if(rvSlider){const track=rvSlider.querySelector('.review-track'),cards=[...track.children],dotsBox=rvSlider.querySelector('.review-dots'),toggle=rvSlider.querySelector('.review-toggle'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,interval=6500;
  let index=0,timer=0,paused=reduce,userPaused=reduce,hover=false;rvSlider.style.setProperty('--rv-interval',interval+'ms');
  const dots=cards.map((c,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('role','tab');b.setAttribute('aria-label','Show review '+(i+1));b.onclick=()=>{go(i);restart()};dotsBox.appendChild(b);return b});
  const perView=()=>innerWidth>1000?2:1;
  const pos=i=>Math.max(0,cards[i].offsetLeft-parseFloat(getComputedStyle(track).paddingLeft));
  const mark=()=>{const left=track.scrollLeft;let best=0,d=1e9;cards.forEach((c,i)=>{const x=Math.abs(pos(i)-left);if(x<d){d=x;best=i}});index=best;const n=perView();cards.forEach((c,i)=>{c.classList.toggle('is-active',i>=index&&i<index+n)});dots.forEach((b,i)=>b.setAttribute('aria-selected',i===index))};
  const go=i=>{index=(i+cards.length)%cards.length;track.scrollTo({left:pos(index),behavior:reduce?'auto':'smooth'})};
  const tick=()=>{clearTimeout(timer);if(paused||hover||document.hidden)return;rvSlider.classList.add('is-playing');timer=setTimeout(()=>{const maxLeft=track.scrollWidth-track.clientWidth;go(track.scrollLeft>=maxLeft-4?0:index+1);tick()},interval)};
  const restart=()=>{rvSlider.classList.remove('is-playing');clearTimeout(timer);void rvSlider.offsetWidth;tick()};
  rvSlider.querySelector('.review-prev').onclick=()=>{go(index-1);restart()};rvSlider.querySelector('.review-next').onclick=()=>{go(index+1);restart()};
  const setPaused=p=>{userPaused=p;paused=p;toggle.setAttribute('aria-pressed',p);toggle.setAttribute('aria-label',p?'Resume automatic scrolling':'Pause automatic scrolling');toggle.firstElementChild.textContent=p?'▶':'❚❚';rvSlider.classList.remove('is-playing');clearTimeout(timer);if(!p)tick()};
  toggle.onclick=()=>setPaused(!userPaused);
  rvSlider.addEventListener('mouseenter',()=>{hover=true;rvSlider.classList.remove('is-playing');clearTimeout(timer)});rvSlider.addEventListener('mouseleave',()=>{hover=false;tick()});
  rvSlider.addEventListener('focusin',()=>{hover=true;clearTimeout(timer)});rvSlider.addEventListener('focusout',()=>{hover=false;tick()});
  rvSlider.addEventListener('touchstart',()=>{hover=true;clearTimeout(timer)},{passive:true});rvSlider.addEventListener('touchend',()=>{hover=false;setTimeout(tick,4000)},{passive:true});
  rvSlider.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){go(index+1);restart()}if(e.key==='ArrowLeft'){go(index-1);restart()}});
  let raf=0;track.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(mark)},{passive:true});addEventListener('resize',mark);document.addEventListener('visibilitychange',()=>document.hidden?clearTimeout(timer):tick());
  if(reduce)toggle.hidden=true;
  const rvIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){paused=userPaused;mark();tick()}else{paused=true;clearTimeout(timer);rvSlider.classList.remove('is-playing')}}),{threshold:.35});rvIO.observe(rvSlider);mark();
 }
 const animated=document.querySelectorAll('.reveal,.reveal-card,.split-reveal');
 if(animated.length){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.16,rootMargin:'0px 0px -8%'});animated.forEach((el,i)=>{if(el.closest('.reference-hero'))setTimeout(()=>el.classList.add('in-view'),160+i*100);else observer.observe(el)})}
}

async function submitForm(e){e.preventDefault();const form=e.currentTarget,status=form.querySelector('.form-status'),button=form.querySelector('button[type=submit]');status.textContent='Sending…';button.disabled=true;const payload=Object.fromEntries(new FormData(form));payload.source=form.dataset.source||'contact';try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not send');status.textContent='Thank you. Your request is in. Expect a reply within one hour.';form.reset()}catch(err){status.innerHTML=`We could not send that just now. Please email <a href="mailto:${SITE.email}">${SITE.email}</a>.`}finally{button.disabled=false}}
document.addEventListener('DOMContentLoaded',init);
function openBooking(){const m=document.getElementById('booking-modal');if(m)m.classList.add('open')}
function closeBooking(){const m=document.getElementById('booking-modal');if(m)m.classList.remove('open')}
