// data.js — shared content for services and contracts. Globals on window.

window.PS_SERVICES = [
  {
    slug: 'proposal-preparation',
    icon: 'pen-tool',
    name: 'Proposal Preparation',
    short: 'End-to-end proposal writing — technical volumes, pricing narratives, compliance matrices, past performance.',
    featured: true,
    long: 'This is the core service. When you bring me a solicitation, I write the entire proposal response — every required volume, mapped section-by-section to the evaluation criteria. Not just answering the question, but writing to how the proposal will be scored.',
    deliverables: [
      'Technical approach volume',
      'Management plan',
      'Past performance documentation',
      'Pricing narrative & schedule',
      'Compliance matrix',
      'All representations and certifications',
      'Final pre-submission compliance review',
      'Submission support'
    ],
    process: 'Typical engagement runs 2 to 6 weeks depending on solicitation complexity. I work to your submission deadline, not mine.',
  },
  {
    slug: 'rfp-analysis',
    icon: 'file-search',
    name: 'RFP & Solicitation Analysis',
    short: 'Detailed breakdown of RFPs and RFQs — risks, requirements, evaluation criteria, and go or no-go recommendation.',
    featured: true,
    long: 'Before you spend money on a proposal, you need to know whether the contract is winnable. I read the full solicitation, identify scoring weights, flag compliance risks, evaluate fit against your capabilities, and give you a clear go or no-go in writing.',
    deliverables: [
      'Section-by-section solicitation summary',
      'Evaluation criteria + scoring weight breakdown',
      'Compliance risk register',
      'Capability gap analysis',
      'Competitor positioning notes',
      'Written go / no-go recommendation',
    ],
    process: 'Turnaround is 48 hours for most solicitations. The first review is free if you are a new client.',
  },
  {
    slug: 'sam-gov-registration',
    icon: 'shield-check',
    name: 'SAM.gov Registration',
    short: 'Full setup and activation of your System for Award Management profile — required for federal contracting.',
    featured: true,
    long: 'You cannot accept a single federal dollar without an active SAM.gov registration. I handle the full process from entity validation through activation: UEI, CAGE Code, NAICS selection, representations and certifications, and the small business profile setup that controls how contracting officers find you.',
    deliverables: [
      'Entity validation & UEI assignment',
      'CAGE Code application',
      'NAICS code selection',
      'Representations & certifications',
      'Small business profile setup',
      'Annual renewal scheduling',
    ],
    process: '2 to 4 weeks end-to-end. Most of the time is government processing, not work.',
  },
  {
    slug: 'sba-certifications',
    icon: 'award',
    name: 'SBA Certifications',
    short: 'Guidance and application support for 8(a), HUBZone, WOSB, EDWOSB, SDVOSB, and VOSB certifications.',
    featured: true,
    long: 'The right certification turns you from one of hundreds of bidders into one of a handful eligible for set-aside contracts. I evaluate which certifications you actually qualify for, prepare the application package, and respond to SBA inquiries until you are certified.',
    deliverables: [
      'Eligibility evaluation across all SBA programs',
      'Application package (forms, narratives, exhibits)',
      'Supporting documentation review',
      'Response to SBA clarification requests',
      'Annual recertification support',
    ],
    process: 'Application prep takes 2 to 6 weeks. SBA decision timelines vary by program.',
  },
  {
    slug: 'capability-statement',
    icon: 'file-text',
    name: 'Capability Statement',
    short: 'A professional one-page capability statement tailored to your target agencies, NAICS codes, and core competencies.',
    featured: true,
    long: 'A capability statement is what a contracting officer looks at for fifteen seconds before deciding whether to call you. Get this wrong and nothing else matters. I write a one-pager that surfaces your differentiators, certifications, codes, and contact in the order a CO scans them.',
    deliverables: [
      'Core competencies narrative',
      'Differentiator block',
      'NAICS / PSC code listing',
      'Certifications & set-asides',
      'Past performance summary',
      'Designed one-page PDF',
    ],
    process: '1 to 2 weeks from kickoff to final PDF.',
  },
  // Non-featured (no detail page) — still listed
  { slug: 'cage-duns', icon: 'fingerprint', name: 'UEI, CAGE Code & DUNS', short: 'Obtaining your Unique Entity Identifier, CAGE Code, and DUNS number to establish federal vendor identity.' },
  { slug: 'opportunity-research', icon: 'search', name: 'Contract Opportunity Research', short: 'Targeted research on federal, state, and local bid opportunities that match your business profile and capacity.' },
  { slug: 'state-local', icon: 'landmark', name: 'State & Local Vendor Registration', short: 'Registration on state procurement portals and local vendor databases for non-federal contracting.' },
  { slug: 'dbe-mbe', icon: 'users', name: 'DBE & MBE Certifications', short: 'Support for Disadvantaged Business Enterprise and Minority Business Enterprise certifications at state and local level.' },
  { slug: 'past-performance', icon: 'briefcase', name: 'Past Performance Documentation', short: 'Writing and formatting of past performance references and contract summaries for proposals and capability packages.' },
  { slug: 'subcontracting', icon: 'layers', name: 'Subcontracting Plans', short: 'Development of small business subcontracting plans required for large prime contracts.' },
  { slug: 'sources-sought', icon: 'inbox', name: 'Sources Sought & RFI Responses', short: 'Drafting responses to Sources Sought notices and RFIs to position your firm ahead of formal solicitations.' },
];

window.PS_CONTRACTS = [
  {
    slug: 'shaw-afb-laundry',
    n: '01',
    title: 'Laundry and Dry Cleaning Services',
    client: 'Tebebi LLC',
    agency: '20th Contracting Squadron, Shaw AFB, SC',
    agencyType: 'Federal',
    valueDisplay: 'Firm-Fixed Unit Price',
    sub: 'Federal · USAF · September 2025',
    fields: [
      ['Solicitation', 'FA480325A0013', true],
      ['Set-Aside', '100% Small Business', false],
      ['Contract Type', 'Firm-Fixed Unit Price', false],
      ['Award Date', 'September 2025', false],
      ['My Role', 'Proposal Strategist & Writer', false],
    ],
    scopeParas: [
      "This contract covered recurring laundry and dry cleaning services for the 23d Force Support Squadron at Shaw AFB, South Carolina. Items included mission-critical gear: JSLIST protective coats and trousers, A3 bags, sleeping bags, helmet covers, parkas, and general garrison items.",
      "The contract required strict compliance with base access protocols, DBIDS enrollment, and EMNS registration for all personnel.",
    ],
    contributionParas: [
      "I managed the full proposal lifecycle. Starting with opportunity identification and RFP analysis, I developed the technical approach, service execution plan, quality control framework, and compliance documentation.",
      "I wrote the complete performance work statement response addressing chain-of-custody procedures, turnaround compliance, security and base access readiness, and unsatisfactory performance protocols. I structured the pricing schedule across all 10 CLINs, developed the staffing and transportation plan, and prepared all representations and certifications.",
    ],
    outcomeHead: 'Contract Awarded',
    outcomeBody: 'Tebebi LLC was awarded this contract to serve Shaw Air Force Base as the sole laundry and dry cleaning provider for the 23d Force Support Squadron. The proposal was accepted in full with no exceptions or requested clarifications.',
  },
  {
    slug: 'winter-park-lot-cleaning',
    n: '02',
    title: 'Lot Cleaning Services for Code Enforcement',
    client: 'Seven Cleaning Service, LLC',
    agency: 'City of Winter Park, Florida',
    agencyType: 'Municipal',
    valueDisplay: '$138,540 / yr est.',
    sub: 'Municipal · July 2024',
    fields: [
      ['Procurement Agent', 'Rebecca Watt', false],
      ['Contract Type', 'Fixed Unit Price', false],
      ['Annual Value', '$138,540 (est.)', false],
      ['Per Cycle', '$11,545', false],
      ['Cert Stack', 'SBA WOSB · EDWOSB · MBE · WBE', false],
      ['My Role', 'Proposal Strategist & Writer', false],
    ],
    scopeParas: [
      "Comprehensive lot cleaning services for the City of Winter Park's Code Enforcement division: grass mowing for residential, commercial, and vacant lots; trimming and edging; full debris and litter removal; herbicide application for weed control; and grading and removal of accumulated dirt.",
      "The contract required photographic documentation, compliance reporting, and safe chemical handling protocols.",
    ],
    contributionParas: [
      "I developed the complete proposal response: cover letter, company history, scope of work response, technical specifications, performance metrics, equipment list, and full fee proposal table across four service categories.",
      "I advised on positioning the client's SBA WOSB, EDWOSB, MBE, and WBE certifications to maximize their evaluation standing.",
    ],
    outcomeHead: 'Contract Awarded',
    outcomeBody: "Seven Cleaning Service, LLC was awarded the lot cleaning contract by the City of Winter Park, Florida. The estimated annual contract value was $138,540. This was the client's entry into municipal government contracting.",
  },
  {
    slug: 'rbha-advertising',
    n: '03',
    title: 'Employment Advertising Services',
    client: '3XG Enterprises LLC',
    agency: 'Richmond Behavioral Health Authority, Richmond, VA',
    agencyType: 'State',
    valueDisplay: 'Up to $124,800 / yr',
    sub: 'State · February 2025 · highest technical rating',
    fields: [
      ['RFP Number', '2025-HR-0004', true],
      ['Contract Type', 'Fixed-Price, Performance-Based', false],
      ['Term', '2-year initial · 4 × 2-year renewals', false],
      ['Annual Value', '$3,200 to $10,400 / mo', false],
      ['My Role', 'Strategist, Writer, Oral Deck Designer', false],
    ],
    scopeParas: [
      "Comprehensive digital employment advertising for the Richmond Behavioral Health Authority: programmatic advertising, geo-fencing, social media campaigns, streaming TV and audio, email marketing, and SEO for job postings.",
      "Required detailed analytics reporting, real-time campaign optimization, and integration with RBHA's internal applicant tracking systems. Initial period two years with four two-year renewal options.",
    ],
    contributionParas: [
      "I managed this engagement from RFP analysis through final award. Developed all six tabs required by the solicitation including qualifications narrative, demonstrated knowledge section, full pricing schedule with two tiered packages, and all compliance attachments.",
      "I positioned the client's existing five-year relationship with RBHA as the central differentiator and built the technical approach around their multi-channel digital capability to establish them as the lowest-risk vendor in the field.",
      "After the proposal received the highest technical rating, the client was invited to a final in-person oral presentation. I developed the full presentation deck and a one-page summary document used during the interview.",
    ],
    outcomeHead: 'Highest-Rated Proposal + Contract Awarded',
    outcomeBody: '3XG Enterprises LLC received the highest technical rating among all competing vendors at the written proposal stage. Following a successful oral presentation using the deck I prepared, RBHA awarded the contract — full-cycle support from written submission through competitive oral presentation, valued at up to $124,800 annually with renewal potential.',
    quote: {
      text: 'Our proposal had the highest rating of all the vendors and I have been invited for a final in-person interview.',
      author: 'Broderick Thomas',
      role: 'CEO, 3XG Enterprises LLC · Richmond, VA',
    },
  },
  {
    slug: 'wright-patterson-bpa',
    n: '04',
    title: 'Laundry Services Blanket Purchase Agreement',
    client: 'Tebebi LLC',
    agency: '711th Human Performance Wing, Wright-Patterson AFB, OH',
    agencyType: 'Federal',
    valueDisplay: 'BPA · 5-year term',
    sub: 'Federal · USAF · Performance start April 2026',
    fields: [
      ['Solicitation', 'COMBO-AFRL-PZLEQ-2026-0003', true],
      ['Contracting Officer', 'Micah Wilson', false],
      ['NAICS', '812332 — Industrial Launderers', false],
      ['Contract Type', 'BPA · Firm-Fixed Unit Price', false],
      ['Performance Start', 'April 1, 2026', false],
      ['My Role', 'Proposal Strategist & Writer', false],
    ],
    scopeParas: [
      "Weekly laundry services for the 711th Human Performance Wing at Wright-Patterson Air Force Base, Ohio. Approximately 235 pounds of weekly laundry volume across three service categories: Operational Equipment (OE), Facility Equipment (FE), and Residential Housing (RH).",
      "Services included standard laundry processing, 160°F thermal treatment for contaminated linens per CDC healthcare standards, separate facility handling for infectious disease items, vehicle sanitation using EPA-approved germicidal agents, minor garment repairs at no additional cost, and 24-hour emergency delivery capability. All pricing was structured FOB Destination to Wright-Patterson AFB.",
    ],
    contributionParas: [
      "I prepared the complete proposal package for this BPA: cover letter, executive summary, technical capability statement, and representations and certifications.",
      "The technical capability statement was structured to address each of the five mandatory acceptability criteria in the Performance Work Statement: 160°F wash capability, separate infectious disease facility, vehicle sanitation compliance, minor repair capability, and 24-hour emergency delivery. I wrote the compliance narrative to directly mirror the PWS requirements section by section, leaving no evaluation gap for the contracting officer.",
      "I also structured the pricing narrative to reflect the three-category service segmentation required by the solicitation and positioned Tebebi LLC as technically compliant and operationally ready for the April 1, 2026 performance start.",
    ],
    outcomeHead: 'Contract Awarded',
    outcomeBody: 'Tebebi LLC was awarded the Laundry Services BPA for the 711th Human Performance Wing at Wright-Patterson Air Force Base. This is the second Air Force base laundry contract won by Tebebi LLC with proposals I prepared, demonstrating repeatable results across different installations and contracting offices.',
  },
];

window.PS_PROCESS = [
  { n: '01', t: 'Opportunity Analysis', d: "I review the full solicitation, evaluate fit against your capabilities, identify evaluation criteria and scoring weights, flag compliance risks, and give you a clear go or no-go recommendation before any writing begins. You never waste money bidding on contracts you cannot win." },
  { n: '02', t: 'Strategy & Research', d: "I map your strengths against the agency's stated priorities, research competing vendors, develop your win themes, and build the pricing strategy. This is where the proposal is won before a single word is written." },
  { n: '03', t: 'Proposal Development', d: "I write all required volumes including technical approach, management plan, past performance, pricing narrative, and compliance matrix. Every section is written to evaluation criteria, not just to answer the question." },
  { n: '04', t: 'Submission & Support', d: "I conduct a final compliance review before submission. After award or rejection I can provide debrief analysis to identify what worked and what to improve on the next bid." },
];
